### ISSUE TITLE
shortcut conflict

### ISSUE THREAD

**Issue by Amarok24** [codeomnitrix/bootstrap-snippets#1]
Hi,
the usage of the following shortcut
Ctrl+Shift+I > Create an input group
is not good, since it is already used by the very popular Emmet extension to "update tag" and I guess most Brackets-users have Emmet installed. 
Could you please consider changing it?

**Comment by codeomnitrix** [comment]
Hey 

Thanks for pointing it out, I actually never tried Emmet. I have kept these kind of shortcuts based on the first letter of the thing to do like navigation, input group etc. I would request you to modify the shortcuts as per your needs by forking it. It won't take more than a minute for you. However due to consistency I would keep the things as it is until multiple requests comes. 

Thanks again
